import Knight from "./icons/knight";
import Pawn from "./icons/pawn";
import Queen from "./icons/queen";
import Rook from "./icons/rook";
import { BoardState } from "./types";

export const levels = [
  {
    id: 1,
    name: "New to chess",
    icon: Pawn,
  },
  {
    id: 2,
    name: "Beginner",
    icon: Knight,
  },
  {
    id: 3,
    name: "Intermediate",
    icon: Rook,
  },
  {
    id: 4,
    name: "Advanced",
    icon: Queen,
  },
];

export const chessPieces = [
  // Black Pieces
  {
    id: "1",
    type: "rook",
    color: "black",
    image: "/br.png",
    initialX: 0,
    initialY: 0,
  },
  {
    id: "2",
    type: "knight",
    color: "black",
    image: "/bn.png",
    initialX: 100,
    initialY: 0,
  },
  {
    id: "3",
    type: "bishop",
    color: "black",
    image: "/bb.png",
    initialX: 200,
    initialY: 0,
  },
  {
    id: "4",
    type: "queen",
    color: "black",
    image: "/bq.png",
    initialX: 300,
    initialY: 0,
  },
  {
    id: "5",
    type: "king",
    color: "black",
    image: "/bk.png",
    initialX: 400,
    initialY: 0,
  },
  {
    id: "6",
    type: "bishop",
    color: "black",
    image: "/bb.png",
    initialX: 500,
    initialY: 0,
  },
  {
    id: "7",
    type: "knight",
    color: "black",
    image: "/bn.png",
    initialX: 600,
    initialY: 0,
  },
  {
    id: "8",
    type: "rook",
    color: "black",
    image: "/br.png",
    initialX: 700,
    initialY: 0,
  },
  {
    id: "9",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 0,
    initialY: 100,
  },
  {
    id: "10",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 100,
    initialY: 100,
  },
  {
    id: "11",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 200,
    initialY: 100,
  },
  {
    id: "12",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 300,
    initialY: 100,
  },
  {
    id: "13",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 400,
    initialY: 100,
  },
  {
    id: "14",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 500,
    initialY: 100,
  },
  {
    id: "15",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 600,
    initialY: 100,
  },
  {
    id: "16",
    type: "pawn",
    color: "black",
    image: "/bp.png",
    initialX: 700,
    initialY: 100,
  },

  // White Pieces
  {
    id: "17",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 0,
    initialY: 600,
  },
  {
    id: "18",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 100,
    initialY: 600,
  },
  {
    id: "19",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 200,
    initialY: 600,
  },
  {
    id: "20",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 300,
    initialY: 600,
  },
  {
    id: "21",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 400,
    initialY: 600,
  },
  {
    id: "22",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 500,
    initialY: 600,
  },
  {
    id: "23",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 600,
    initialY: 600,
  },
  {
    id: "24",
    type: "pawn",
    color: "white",
    image: "/wp.png",
    initialX: 700,
    initialY: 600,
  },
  {
    id: "25",
    type: "rook",
    color: "white",
    image: "/wr.png",
    initialX: 0,
    initialY: 700,
  },
  {
    id: "26",
    type: "knight",
    color: "white",
    image: "/wn.png",
    initialX: 100,
    initialY: 700,
  },
  {
    id: "27",
    type: "bishop",
    color: "white",
    image: "/wb.png",
    initialX: 200,
    initialY: 700,
  },
  {
    id: "28",
    type: "queen",
    color: "white",
    image: "/wq.png",
    initialX: 300,
    initialY: 700,
  },
  {
    id: "29",
    type: "king",
    color: "white",
    image: "/wk.png",
    initialX: 400,
    initialY: 700,
  },
  {
    id: "30",
    type: "bishop",
    color: "white",
    image: "/wb.png",
    initialX: 500,
    initialY: 700,
  },
  {
    id: "31",
    type: "knight",
    color: "white",
    image: "/wn.png",
    initialX: 600,
    initialY: 700,
  },
  {
    id: "32",
    type: "rook",
    color: "white",
    image: "/wr.png",
    initialX: 700,
    initialY: 700,
  },
] as const;

export const initialBoardState: BoardState = chessPieces.reduce(
  (acc, piece) => {
    acc[piece.id] = {
      x: piece.initialX,
      y: piece.initialY,
      type: piece.type,
      color: piece.color,
    };
    return acc;
  },
  {} as BoardState
);

export const pieces = [
  "wP",
  "wN",
  "wB",
  "wR",
  "wQ",
  "wK",
  "bP",
  "bN",
  "bB",
  "bR",
  "bQ",
  "bK",
];

export const bots = {
  beginner: [
    {
      id: 1,
      name: "Martin",
      level: 1,
      image: "/martin.png",
      country: "BG",
      elo: "250",
    },
    {
      id: 2,
      name: "Juan",
      level: 2,
      image: "/juan.png",
      country: "PL",
      elo: "400",
    },
    {
      id: 3,
      name: "Milica",
      level: 3,
      image: "/milica.png",
      country: "RS",
      elo: "550",
    },
  ],
};
